# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rate-limit-plugin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rate-limit-plugin.proto\x12\x05proto\"I\n\x16RateLimitPluginRequest\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.proto.RatelimitType\x12\x0b\n\x03key\x18\x02 \x01(\t\"(\n\x17RateLimitPluginResponse\x12\r\n\x05\x61llow\x18\x01 \x01(\x08*_\n\rRatelimitType\x12\x0f\n\x0bIPRatelimit\x10\x00\x12\x10\n\x0c\x41PIRatelimit\x10\x01\x12\x14\n\x10ServiceRatelimit\x10\x02\x12\x15\n\x11InstanceRatelimit\x10\x03\x42,\n\x15\x63n.polaris.plugin.apiB\tRateLimitP\x00Z\x06./;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rate_limit_plugin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025cn.polaris.plugin.apiB\tRateLimitP\000Z\006./;api'
  _RATELIMITTYPE._serialized_start=151
  _RATELIMITTYPE._serialized_end=246
  _RATELIMITPLUGINREQUEST._serialized_start=34
  _RATELIMITPLUGINREQUEST._serialized_end=107
  _RATELIMITPLUGINRESPONSE._serialized_start=109
  _RATELIMITPLUGINRESPONSE._serialized_end=149
# @@protoc_insertion_point(module_scope)
